# Generated by Django 5.2.10 on 2026-01-26 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("DEACTIVATED", "DEACTIVATED"),
                            ("BANNED", "BANNED"),
                            ("DORMANT", "DORMANT"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("USER", "User"),
                            ("INSTRUCTOR", "Instructor"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "password_reset_requests",
            },
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("EMAIL", "email"), ("PHONE", "phone")], max_length=10
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text="EMAIL일 시 email 입력, PHONE일 시 phone 저장",
                        max_length=150,
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("EMAIL_SIGNUP", "email_signup"),
                            ("EMAIL_PASSWORD_RESET", "email_password_reset"),
                            ("PHONE_SIGNUP", "phone_signup"),
                            ("PHONE_PASSWORD_RESET", "phone_password_reset"),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "verifications",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "EMAIL"), ("purpose__startswith", "EMAIL_")
                            ),
                            models.Q(
                                ("status", "PHONE"), ("purpose__startswith", "PHONE_")
                            ),
                            _connector="OR",
                        ),
                        name="ck_verification_purpose_match_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "created_at"),
                        name="attendance_record_once_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE", "G"), ("KAKAO", "K")], max_length=12
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                ("social_email", models.CharField(max_length=255)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "oauth_accounts",
                "indexes": [
                    models.Index(fields=["user"], name="idx_oauth_user"),
                    models.Index(fields=["provider"], name="idx_oauth_provider"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="unique_oauth_provider_provider_user_id",
                    )
                ],
            },
        ),
    ]
