# Generated by Django 5.2.10 on 2026-02-04 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=10)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("profile_image_url", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("DEACTIVATED", "DEACTIVATED"),
                            ("BANNED", "BANNED"),
                            ("DORMANT", "DORMANT"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Admin"),
                            ("USER", "User"),
                            ("INSTRUCTOR", "Instructor"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("agree_marketing", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "attendance_records",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "created_at"),
                        name="attendance_record_once_per_day",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OAuthAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE", "G"), ("KAKAO", "K")], max_length=12
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "oauth_accounts",
                "indexes": [
                    models.Index(fields=["user"], name="idx_oauth_user"),
                    models.Index(fields=["provider"], name="idx_oauth_provider"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_user_id"),
                        name="unique_oauth_provider_provider_user_id",
                    )
                ],
            },
        ),
    ]
