# Generated by Django 5.2.10 on 2026-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_delete_verification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oauthaccount",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="oauthaccount",
            name="refresh_token",
        ),
        migrations.RemoveField(
            model_name="oauthaccount",
            name="social_email",
        ),
        migrations.AddField(
            model_name="user",
            name="agree_marketing",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="PasswordResetRequest",
        ),
    ]
