# Generated by Django 5.2.10 on 2026-01-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_phoneverification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerification",
        ),
        migrations.DeleteModel(
            name="PhoneVerification",
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("DEACTIVATED", "DEACTIVATED"),
                    ("BANNED", "BANNED"),
                    ("DORMANT", "DORMANT"),
                ],
                default="ACTIVE",
                max_length=12,
            ),
        ),
    ]
