[tool.poetry]
name = "studigo"
version = "0.1.0"
description = ""
authors = ["minjukim <minjuju0518@naver.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.1"
gunicorn = "^23.0.0"

[tool.poetry.group.dev.dependencies]
black = "^25.12.0"
isort = "^7.0.0"
mypy = "^1.19.1"
django-stubs = "^5.2.8"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py312"]
exclude = '''
/(
    migrations
  | venv
  | .venv
  | node_modules
  | staticfiles
)/
'''

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["apps", "config"]
skip = ["migrations", "staticfiles"]

[tool.mypy]
python_version = "3.12"
plugins = ["mypy_django_plugin.main"]
ignore_missing_imports = true
strict = true
warn_unused_configs = true
exclude = 'migrations|staticfiles'

[tool.django-stubs]
django_settings_module = "config.settings"
strict_settings = true
