# Generated by Django 5.2.10 on 2026-01-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quote_date", models.DateField(unique=True)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "daily_quotes",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100, verbose_name="문제 제목")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="문제 설명"),
                ),
                ("prompt", models.TextField(verbose_name="문제 내용")),
                (
                    "answer_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="빈칸 정답"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="해설"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
            ],
            options={
                "verbose_name": "문제",
                "verbose_name_plural": "문제",
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="DailyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_date",
                    models.DateField(
                        help_text="해당 날짜에 제공되는 오늘의 문제 (하루 1문제)",
                        unique=True,
                        verbose_name="문제 날짜",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_questions",
                        to="daily.question",
                        verbose_name="문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "오늘의 문제",
                "verbose_name_plural": "오늘의 문제",
                "db_table": "daily_questions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question_date",), name="uk_daily_questions_date"
                    )
                ],
            },
        ),
    ]
