# Generated by Django 5.2.10 on 2026-01-30 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daily", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyQuestionSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_answer_text",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="제출한 답변",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="정답 여부"),
                ),
                (
                    "daily_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="daily.dailyquestion",
                        verbose_name="오늘의 문제",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_question_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("daily_question", "user"),
                        name="uk_daily_question_submission_user",
                    )
                ],
            },
        ),
    ]
