POST_VIEW_TTL_SECONDS = 60 * 10

# 로그인 연속 실패 기준
LOGIN_FAIL_BLOCK_COUNT_1 = 5
LOGIN_FAIL_BLOCK_COUNT_2 = 10

# 로그인 연속 실패시 차단 시간
LOGIN_FAIL_BLOCK_TIME_1 = 60 * 10  # 10분
LOGIN_FAIL_BLOCK_TIME_2 = 60 * 60  # 1시간

# 로그인 연속 실패 기준 시간
LOGIN_FAIL_COUNTER_TTL = 60 * 60 * 2  # 2시간

# Access Token
JWT_ACCESS_TOKEN_LIFETIME = 60 * 60  # 1시간

# Refresh Token
JWT_REFRESH_TOKEN_LIFETIME = 60 * 60 * 24  # 24시간
JWT_REFRESH_TOKEN_LIFETIME_REMEMBERME = 60 * 60 * 24 * 30  # 30일

# 이메일/닉네임 중복 확인 만료 시간
SIGNUP_CHECK_TTL = 60 * 5  # 5분

# 이메일 인증
EMAIL_VERIFICATION_TTL = 60 * 3
EMAIL_VERIFICATION_COOLDOWN = 30
EMAIL_VERIFICATION_MAX_ATTEMPTS = 5
EMAIL_VERIFICATION_LIMIT_PER_HOUR = 3

# OAuth Redis TTL
OAUTH_STATE_TTL = 60 * 10
SOCIAL_SIGNUP_SESSION_TTL = 60 * 30
