# Generated by Django 5.2.10 on 2026-02-04 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RECRUIT", "모집 게시판"),
                            ("STUDY", "학습 게시판"),
                            ("FREE", "자유 게시판"),
                        ],
                        default="FREE",
                        max_length=10,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "공개"),
                            ("BLINDED", "비공개"),
                            ("DELETED", "삭제"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "blinded_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("view_count", models.BigIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "공개"),
                            ("BLINDED", "비공개"),
                            ("DELETED", "삭제"),
                        ],
                        default="ACTIVE",
                    ),
                ),
                (
                    "blinded_reason",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("blinded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_url", models.URLField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="community.post",
                    ),
                ),
            ],
            options={
                "db_table": "post_images",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="community.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post_likes",
            },
        ),
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "진행중"),
                            ("RESOLVED", "승인"),
                            ("REJECTED", "거부"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reports",
                        to="community.post",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post_reports",
            },
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "진행중"),
                            ("RESOLVED", "승인"),
                            ("REJECTED", "거부"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports",
                        to="community.comment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_reports",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="comment_rep_status_b113a1_idx",
                    ),
                    models.Index(
                        fields=["comment", "created_at"],
                        name="comment_rep_comment_2bcfb2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comment", "reporter"),
                        name="unique_comment_reports_comment_reporter",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "created_at"], name="posts_author__d19a82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "created_at"], name="posts_status_def373_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="comments_post_id_015fcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "created_at"], name="comments_author__b3902f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["status", "created_at"], name="comments_status_488383_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postimage",
            index=models.Index(
                fields=["post", "sort_order"], name="post_images_post_id_47aa54_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postimage",
            constraint=models.UniqueConstraint(
                fields=("post", "image_url"), name="unique_post_images_post_image_url"
            ),
        ),
        migrations.AddIndex(
            model_name="postlike",
            index=models.Index(
                fields=["user", "created_at"], name="post_likes_user_id_eb9740_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postlike",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_post_likes_user_post"
            ),
        ),
        migrations.AddIndex(
            model_name="postreport",
            index=models.Index(
                fields=["post", "created_at"], name="post_report_post_id_e381a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postreport",
            index=models.Index(
                fields=["reporter", "created_at"], name="post_report_reporte_6520dd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="postreport",
            constraint=models.UniqueConstraint(
                fields=("post", "reporter"), name="unique_post_reports_post_reporter"
            ),
        ),
    ]
