# Generated by Django 5.2.10 on 2026-01-26 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "진행중"),
                            ("RESOLVED", "승인"),
                            ("REJECTED", "거부"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.post",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post_reports",
                "indexes": [
                    models.Index(
                        fields=["post", "created_at"],
                        name="post_report_post_id_e381a5_idx",
                    ),
                    models.Index(
                        fields=["reporter", "created_at"],
                        name="post_report_reporte_6520dd_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "reporter"),
                        name="unique_post_reports_post_reporter",
                    )
                ],
            },
        ),
    ]
