# Generated by Django 5.2.10 on 2026-01-29 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_postreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="postreport",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reports",
                to="community.post",
            ),
        ),
        migrations.AlterField(
            model_name="postreport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "진행중"),
                            ("RESOLVED", "승인"),
                            ("REJECTED", "거부"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports",
                        to="community.comment",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "comment_reports",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="comment_rep_status_b113a1_idx",
                    ),
                    models.Index(
                        fields=["comment", "created_at"],
                        name="comment_rep_comment_2bcfb2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comment", "reporter"),
                        name="unique_comment_reports_comment_reporter",
                    )
                ],
            },
        ),
    ]
