# Generated by Django 5.2.10 on 2026-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_postreport_post_alter_postreport_reporter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("RECRUIT", "모집 게시판"),
                    ("STUDY", "학습 게시판"),
                    ("FREE", "자유 게시판"),
                ],
                default="FREE",
                max_length=10,
            ),
        ),
    ]
