name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: studigo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:latest
        ports:
          - 6379:6379


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-root

      - name: Create env file
        run: |
          echo "${{ secrets.DJANGO_ENVS }}" > .env

      - name: Black
        run: poetry run black . --check

      - name: Isort
        run: poetry run isort . --check-only

      - name: Mypy
        run: poetry run mypy .

      - name: Django Check
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/studigo
        run: poetry run python manage.py check
