# Generated by Django 5.2.10 on 2026-01-23 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_membership",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("participant_count", models.IntegerField()),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="chat_room_created_a10133_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="chat_room_updated_5097bc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("DELETED_BY_ADMIN", "Deleted By Admin"),
                        ],
                        default="SENT",
                        max_length=50,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="chat.membership",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "db_table": "chat_message",
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="chat.room",
            ),
        ),
        migrations.CreateModel(
            name="Bans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bans",
                        to="chat.room",
                    ),
                ),
            ],
            options={
                "db_table": "chat_bans",
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_language",
                    models.CharField(
                        choices=[("ko", "Ko"), ("es", "Es")], default="ko"
                    ),
                ),
                ("translated_text", models.TextField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.message"
                    ),
                ),
            ],
            options={
                "db_table": "chat_translation",
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["room", "created_at"], name="idx_chat_room_created_at"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["user", "joined_at"], name="idx_chat_user_joined_at"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("room", "user"), name="unique_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="bans",
            index=models.Index(
                fields=["user", "is_active"], name="chat_bans_user_id_5eb021_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bans",
            index=models.Index(
                fields=["room", "is_active"], name="chat_bans_room_id_345ed1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bans",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("room__isnull", False)),
                fields=("user", "room"),
                name="unique_bans",
            ),
        ),
        migrations.AddConstraint(
            model_name="bans",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("room__isnull", True)),
                fields=("user",),
                name="unique_bans_user",
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["message", "target_language"],
                name="chat_transl_message_3e4100_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=("message", "target_language"),
                name="uq_chat_translation_message_target_lang",
            ),
        ),
    ]
