# Generated by Django 5.2.10 on 2026-01-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_translation_message"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="room",
            name="chat_room_updated_5097bc_idx",
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="last_message_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["last_message_at"], name="chat_room_last_me_4ba805_idx"
            ),
        ),
    ]
