# Generated by Django 5.2.10 on 2026-02-02 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_translation_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "chat_message_reports",
            },
        ),
        migrations.RemoveIndex(
            model_name="room",
            name="chat_room_updated_5097bc_idx",
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="last_message_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["last_message_at"], name="chat_room_last_me_4ba805_idx"
            ),
        ),
        migrations.AddField(
            model_name="messagereport",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="chat.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereport",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_message_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="messagereport",
            index=models.Index(
                fields=["message_id", "created_at"], name="idx_mr_msg_ct"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereport",
            index=models.Index(
                fields=["reporter_id", "created_at"], name="idx_mr_rep_ct"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereport",
            constraint=models.UniqueConstraint(
                fields=("message", "reporter"), name="uq_msg_report_message_reporter"
            ),
        ),
    ]
