# Generated by Django 5.2.10 on 2026-02-02 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_messagereport_and_more"),
        ("chat", "0003_remove_room_chat_room_updated_5097bc_idx_and_more"),
    ]

    operations = []
